### PR TITLE
Add Events for Previous, Next, First, and Last Page Clicks

### PR DESCRIPTION
**Pull request by kevingilbert100**
This PR adds events for different page events.

`function(event, pageNumber)`

`onPrevPage` | Function | | Will fire in addition to onChange if the previous page button is clicked.
`onNextPage` | Function | | Will fire in addition to onChange if the next page button is clicked.
`onFirstPage` | Function | | Will fire in addition to onChange if the first page button is clicked.
`onLastPage` | Function | | Will fire in addition to onChange if the last page button is clicked.

### CODE REVIEW

**Comment by kevingilbert100** [comment]
@vayser I believe this is essential and should make it into the next version.

**Comment by kevingilbert100** [comment]
@vayser PING

**Comment by mcmcphillips** [comment]
Why was this issue closed? @kevingilbert100

**Comment by kevingilbert100** [comment]
No response from OP

**Comment by kevingilbert100** [comment]
I'd recommend maybe trying another library or forking.

**Comment by mcmcphillips** [comment]
I agree with that. It definitely helps to be able to track page clicks accurately.

**Pull request closed without merging**
