### PR TITLE
Master

### PR DESCRIPTION
**Pull request by pjb0811**
- If the first page and the last page are the same, display the page number
- Add a description for activeFirstPage
- Add react-syntax-highlighter

### CODE REVIEW

**Comment by wagoid** [comment]
@pjb0811 you have failing tests on CI. Do you mind fixing them?

**Comment by vayser** [comment]
@wagoid, i am not sure that PR is correct. Pagination should not be visible if there is only one page of items

**Comment by wagoid** [comment]
@vayser don't you think it would be good to have such an option? I mean, by default it can still hide the page, but it would be nice to have this configurable.

**Comment by wagoid** [comment]
Closing due to stale.

**Pull request closed without merging**
